language: python
sudo: required
dist: xenial
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
env:
- DJANGO_VERSION=1.8
- DJANGO_VERSION=1.11
- DJANGO_VERSION=2.0
matrix:
  exclude:
    - python: '2.7'
      env: 'DJANGO_VERSION=2.0'
install:
- pip install -U django==$DJANGO_VERSION
script: python manage.py test
